facebook_app_id: "1699651200248987"
facebook_app_secret: "20615067a35b5f7354d4ccff5696f75d"

twitter_app_id: "3D3wIwG3iu7VOMHae2NazrlrI"
twitter_app_secret: "KbaUTsTQxXLhG9EyLooXhpaZfiEGEb14r1VMFQ4ZSabJqVIuNU"

google_app_id: "346179712035-8nco99a0bm87arjuatg98bojtp5gj6ag.apps.googleusercontent.com"
google_app_secret: "ANg4-pWpZj_6dkRDomKcHRKW"

GOOGLE_MAIL: "workdeycomet@gmail.com"
GOOGLE_PASSWORD: "s1mulat1ons1n@nd3l@"

DB_PASSWORD: "dbenginE"